### ISSUE TITLE
no documentation?

### ISSUE THREAD

**Issue by Multi-Thinker** [Aerolab/iojs-colorpicker#3]
Hi, do you have a plan to document this color picker? although its nice

**Comment by RobertoGonzalez** [comment]
@Multi-Thinker Not really. It was more of a throwaway experiment to present our concept for io.js and how it could be customized. 
However, the code is relatively simple and the only interesting thing there is that the randomizer picks complementary colors to create somewhat decent palettes on the updateColors function. You can check put the js/scripts.js file to get a look at how it works :D
